---
- name: "Creates SSH key"
  ansible.builtin.command: "ssh-keygen -o -a 200 -t ed25519 -C '{{ ansible_hostname }}' -f {{ ssh_github_key_path }} -N {{ ssh_passphrase }}"
  args:
    creates: "{{ ssh_github_key_path }}"

- name: "Fetch public key Please add this to github"
  ansible.builtin.debug:
    var: item
  with_file:
  - "{{ ssh_github_key_path }}.pub"
