---
- name: "Creates SSH folder"
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.ssh"
    state: directory
    mode: "0700"

- name: "Creates SSH config"
  ansible.builtin.template:
    src: ssh_config.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.ssh/config"
    mode: "0700"

- name: "Create ssh key"
  ansible.builtin.include_tasks: create_ssh_key.yml
