---
- name: "Creates SSH folder"
  file: 
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700

- name: "Creates SSH config"
  template:
    src: ssh_config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: 0700

- include: github.yml
